spring:
  application:
    name: smart-investment
  main:
    banner-mode: "console"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always
    url: jdbc:h2:~/test
    platform: h2
    schema: classpath:data/schema.sql
    data: classpath:data/data.sql
    username: sa
    password:
    driver-class-name: org.h2.Driver